### ISSUE TITLE
Database Migrations in run.sh

### ISSUE THREAD

**Issue by salian** [fe01134/djangobluemix#1]
Using South or the in-built migrations is such a common part of deploying a Django app, that you could consider putting those lines into the run.sh, perhaps commented out with an explanation.

Something to the order of

```
#Uncomment to enable database migrations
python manage.py makemigrations 
python manage.py migrate
```

This would be helpful for someone who is new enough to need djangobluemix.

**Comment by fe01134** [comment]
Hi This has been updated to now support changes to support django 1.9.
